### PR TITLE
Added telugu locale

### LINKED ISSUE #30: Feature: Add language support for Telugu(te)
Overview:

Currently, the main page of the IndiaVaccine Website is in English & Hindi. We'd like to make the content accessible to more people around the country. In order to do so, we've had translators convert the content into Telugu.

Task Details
We're using . You will need to take the content in Telugu from the document below & update it so that the text appears on the website.

Translation document: https://docs.google.com/spreadsheets/d/1WAnvR9CTLdVDaX5GTLzcNI8mAdeG92JYKT_zoSBcn8Y/edit#gid=1358420706

Task List:

- [ ]  Add Telugu language hyperlink on the main page
- [ ]  Update the overall content with the Telugu translation

### PR DESCRIPTION
**Pull request by g-savitha**
Fixes https://github.com/IndiaVaccineIN/india-vaccine-frontend/issues/30

### CODE REVIEW

**Review by preetjdp — APPROVED** [review]
LGTM

**Comment by g-savitha** [comment]
@preetjdp can you merge this?

**Review by g-savitha — COMMENTED** [review]
Resolved merge conflicts

**Comment by g-savitha** [comment]
Hey, @preetjdp I don't see my merged code in the final output of https://www.indiavaccine.in/ . Does it need to be deployed yet?

**Pull request merged**
