### PR TITLE
Added no results message

### PR DESCRIPTION
**Pull request by shubh128**
Resolved Issue #16 
No results available message shown if no vaccination centres are available
image

### CODE REVIEW

**Comment by preetjdp** [comment]
@shubh128 There seem to be some extra linting changes in the PR

Could you run the following command and push that changes?

```bash
npm run prettify
```

**Comment by preetjdp** [comment]
It shows `No results available` when the page data is loading

It should show `No results available` only when the API returns no data, could you handle this case?

https://user-images.githubusercontent.com/27439197/117145283-9e906c80-add0-11eb-9d0a-ec0cfb248ea4.mov

**Comment by shubh128** [comment]
Sure I'll look into this

**Comment by shubh128** [comment]
Fixed the double message bug
However running `npm run prettify` doesn't change anything in `availability_results.tsx`

**Pull request merged**
