### PR TITLE
Fixed edit state/PIN issue. Issue #15.

### PR DESCRIPTION
**Pull request by HarshInvader**
LGTM! This fix works for now but we can later explore a more "best-practices" way to do this.

### CODE REVIEW

**Comment by HarshInvader** [comment]
@shubh128 Could you check the failed checks

**Comment by shubh128** [comment]
@HarshInvader I think i'm not authorized to see the Vercel details page for the failed checks

**Comment by preetjdp** [comment]
> @HarshInvader I think i'm not authorized to see the Vercel details page for the failed checks

@shubh128 Can you rebase your PR with the `dev` branch?

That should fix the build error

**Comment by shubh128** [comment]
@preetjdp I think the PR was created by deepak. Harsha just asked me to figure out why the vercel checks were failing

**Comment by preetjdp** [comment]
> @preetjdp I think the PR was created by deepak. Harsha just asked me to figure out why the vercel checks were failing

Oh my bad, sorry with rectify with @HarshInvader

**Comment by preetjdp** [comment]
@deepak1235 There was a build error caused by a `//@ts-expect-error` fixed it

**Pull request merged**
